# Generated by Django 4.2.7 on 2023-11-10 18:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.fields.StreamField([('contacts', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'image', 'link', 'document-link'], verbose_name='Контакты'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', verbose_name='Заголовок')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'link', 'document-link'], verbose_name='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navbar',
            field=wagtail.fields.StreamField([('logo', wagtail.images.blocks.ImageChooserBlock()), ('menu_item', wagtail.blocks.RichTextBlock(features=['link'], help_text='Пункт меню'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_bg',
            field=models.ForeignKey(blank=True, help_text='Фон страницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
