# Generated by Django 4.2.7 on 2023-11-11 22:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navbar',
            field=wagtail.fields.StreamField([('logo', wagtail.images.blocks.ImageChooserBlock()), ('menu_item', wagtail.blocks.PageChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
